server:
  port: 8008
spring:
  cloud:
    gateway:
      routes:
      - id: service-edu
        URI: lb://service-edu
        predicates:
          Path: "/edu/*/**"
    discovery:
        locator:
          enabled: true
    nacos:
      discovery:
        server-addr: 39.105.154.47:8848